# Generated by Django 6.0 on 2026-01-15 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_an', models.AutoField(db_column='id_an', primary_key=True, serialize=False)),
                ('answers', models.TextField(db_column='answers')),
                ('created_at_answer', models.DateTimeField(db_column='created_at_answer', default=django.utils.timezone.now)),
                ('id_u', models.ForeignKey(db_column='id_u', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_q', models.AutoField(db_column='id_q', primary_key=True, serialize=False)),
                ('title_question', models.CharField(db_column='title_question', max_length=255)),
                ('question', models.TextField(db_column='question')),
                ('created_at_question', models.DateTimeField(db_column='created_at_question', default=django.utils.timezone.now)),
                ('has_answers', models.BooleanField(db_column='has_answers', default=False)),
                ('correct_answer', models.ForeignKey(blank=True, db_column='correct_answer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.answer')),
                ('id_u', models.ForeignKey(db_column='id_u', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='id_q',
            field=models.ForeignKey(db_column='id_q', on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id_vq', models.AutoField(db_column='id_vq', primary_key=True, serialize=False)),
                ('vote_value', models.SmallIntegerField(db_column='vote_value')),
                ('id_q', models.ForeignKey(db_column='id_q', on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('id_u', models.ForeignKey(db_column='id_u', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'QuestionVotes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_t', models.AutoField(db_column='id_t', primary_key=True, serialize=False)),
                ('tag', models.CharField(db_column='tag', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Tags',
                'indexes': [models.Index(fields=['tag'], name='idx_tags_tag')],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id_qt', models.AutoField(db_column='id_qt', primary_key=True, serialize=False)),
                ('id_q', models.ForeignKey(db_column='id_q', on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('id_t', models.ForeignKey(db_column='id_t', on_delete=django.db.models.deletion.RESTRICT, to='questions.tag')),
            ],
            options={
                'db_table': 'QuestionTags',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', through='questions.QuestionTag', to='questions.tag'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_v', models.AutoField(db_column='id_v', primary_key=True, serialize=False)),
                ('vote_value', models.SmallIntegerField(db_column='vote_value')),
                ('id_an', models.ForeignKey(db_column='id_an', on_delete=django.db.models.deletion.CASCADE, to='questions.answer')),
                ('id_u', models.ForeignKey(db_column='id_u', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Votes',
            },
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['id_q'], name='idx_answers_question'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['id_u'], name='idx_answers_user'),
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('id_u', 'id_q')},
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['id_q'], name='idx_questiontags_question'),
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['id_t'], name='idx_questiontags_tag'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together={('id_q', 'id_t')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['id_u'], name='idx_questions_user'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('id_u', 'id_an')},
        ),
    ]
