# Generated by Django 6.0 on 2026-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at_answer',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at_question',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
